#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/5179c0f6-64a1-4388-b392-c95eb253d388 # 
title: Order Fulfillment API
version: v1.0
mediaType: [application/json]

types:
  OrderItem: !include /exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/sap-order-item/1.0.2/sap-order-item.raml
  Order: !include /exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/sap-internal-order/1.0.4/sap-internal-order.raml
  Location: !include /exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/location/1.0.0/location.raml

resourceTypes: 
  orderType: !include /exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/order-post-resource-type/1.0.0/order-post-resource-type.raml
  statusResourceType: !include /exchange_modules/de6ca85b-7dfb-44bc-abb4-388e2dfad3d0/statusresource/1.0.1/statusresource.raml

traits:
  client-id-secured: !include /exchange_modules/com.mythical.retailer.corporateit.traits/client-id-secured-trait/1.0.1/client-id-secured.raml


/orders:
  type: orderType
  post:
    is: [client-id-secured]
    body: 
      type: Order
      example: !include examples/order_post_request.raml
    responses: 
      201:
        body: 
          example: !include examples/order_post_response.raml
  /{id}/status:
    type: statusResourceType
    get:
      is: [client-id-secured]
      responses: 
        200:
          body:
            example: !include examples/status_get_response.raml
        400:
          body:
            example: !include examples/bad_request.raml
        404:
          body:
            example: !include examples/order_not_found.raml
    put:
      is: [client-id-secured]
      responses: 
        200:
          body:
            example: !include examples/status_get_response.raml
        400:
          body:
            example: !include examples/bad_request.raml
        404:
          body:
            example: !include examples/order_not_found.raml   
      