#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/5179c0f6-64a1-4388-b392-c95eb253d388 # 
title: Order Fulfillment API
version: v1.0
mediaType: [application/json]

types:
  OrderItem: !include datatypes/orderItem.raml
  Order: !include datatypes/order.raml
  Location: !include datatypes/location.raml  

resourceTypes: 
  orderType: !include resourceTypes/order.raml  

/orders:
  type: orderType
  post:
    body: 
      type: Order
      example: !include examples/order_post_request.raml
    responses: 
      201:
        body: 
          example: !include examples/order_post_response.raml
      