#%RAML 1.0
title: Order Fulfillment API
version: v1.0
baseUri: https://mocksvc.mulesoft.com/mocks/55a8d638-e536-432f-9d21-e3099301316f/mocks/e0d30c40-6b98-4461-b545-9819bc2349f0/api # baseUri: https://mocksvc.mulesoft.com/mocks/e0d30c40-6b98-4461-b545-9819bc2349f0/api

types:
  OrderItem: !include datatypes/orderItem.raml
  Order: !include datatypes/order.raml
  Location: !include datatypes/location.raml  

/orders:
  post:
    body: 
      application/json: 
        type: Order
        example: !include examples/order_post_request.raml
    responses:
      201: 
        body: 
          application/json: 
            example: !include examples/order_post_response.raml