#%RAML 1.0 NamedExample
value: |
  {
    "customerId" : "1",
    "orderItems": [
      {
        "itemId": "1",
        "productId": "1",
        "location" : {
          "locationId": "1",
          "locationType": "STORE",
          "deliveryMethod": "PICKUP"
        },
        "price": "40", 
        "name": "Supersonic Electronic",
        "quantity": 4
      }
    ],
    "status": "draft",
    "price": "1304"
  }